# Generated by Django 3.1.3 on 2020-11-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ans_count',
            field=models.IntegerField(default=0),
        ),
    ]
